#include "vpu/executor.h"
#include "vpu/alu.h"
#include "vpu/flags.h"
#include "vpu/decoder.h"
#include <string.h>
static vpu_status_t rr(vpu_core_t*c,unsigned i,uint64_t*v){return vpu_reg_read(&c->ctx.regs,i,v);}
static vpu_status_t rw(vpu_core_t*c,unsigned i,uint64_t v){return vpu_reg_write(&c->ctx.regs,i,v);}
static vpu_status_t stack_push(vpu_core_t*c,uint64_t v){if(c->ctx.regs.sp<8)return VPU_ERR_BOUNDS;c->ctx.regs.sp-=8;return vpu_memory_write(&c->memory,c->ctx.regs.sp,&v,8);}
static vpu_status_t stack_pop(vpu_core_t*c,uint64_t*v){if(c->memory.size<8||c->ctx.regs.sp>c->memory.size-8)return VPU_ERR_BOUNDS;vpu_status_t s=vpu_memory_read(&c->memory,c->ctx.regs.sp,v,8);if(!s)c->ctx.regs.sp+=8;return s;}
vpu_status_t vpu_execute_instruction(vpu_core_t*c,const vpu_instruction_t*i){if(!c||!i)return VPU_ERR_NULL;if(c->ctx.state==VPU_CORE_HALTED)return VPU_ERR_HALTED;uint64_t a=0,b=0,r=0,f=0;vpu_status_t s=VPU_OK;switch(i->opcode){case VPU_OP_NOP:break;case VPU_OP_MOV:if(i->flags&1)r=(uint64_t)i->imm;else{s=rr(c,i->src,&r);}if(!s)s=rw(c,i->dst,r);break;case VPU_OP_LOAD:r=(uint64_t)i->imm;if(r>c->memory.size||8>c->memory.size-r)s=VPU_ERR_BOUNDS;else s=vpu_memory_read(&c->memory,(size_t)r,&r,8);if(!s)s=rw(c,i->dst,r);break;case VPU_OP_STORE:s=rr(c,i->src,&r);if(!s&&((uint64_t)i->imm>c->memory.size||8>c->memory.size-(size_t)i->imm))s=VPU_ERR_BOUNDS;if(!s)s=vpu_memory_write(&c->memory,(size_t)i->imm,&r,8);break;case VPU_OP_ADD:case VPU_OP_SUB:case VPU_OP_MUL:case VPU_OP_DIV:case VPU_OP_MOD:case VPU_OP_AND:case VPU_OP_OR:case VPU_OP_XOR:case VPU_OP_SHL:case VPU_OP_SHR:case VPU_OP_CMP:s=rr(c,i->dst,&a);if(!s)s=rr(c,i->src,&b);if(!s){vpu_alu_op_t op=(vpu_alu_op_t)(i->opcode-VPU_OP_ADD);s=vpu_alu_exec(op,a,b,&r,&f);}if(!s){c->ctx.regs.flags=f;if(i->opcode!=VPU_OP_CMP)s=rw(c,i->dst,r);}break;case VPU_OP_NOT:s=rr(c,i->dst,&a);if(!s)s=vpu_alu_exec(VPU_ALU_NOT,a,0,&r,&f);if(!s){c->ctx.regs.flags=f;s=rw(c,i->dst,r);}break;case VPU_OP_JMP:c->ctx.regs.pc=(uint64_t)i->imm;return VPU_OK;case VPU_OP_JE:if(c->ctx.regs.flags&VPU_FLAG_ZERO)c->ctx.regs.pc=i->imm;return VPU_OK;case VPU_OP_JNE:if(!(c->ctx.regs.flags&VPU_FLAG_ZERO))c->ctx.regs.pc=i->imm;return VPU_OK;case VPU_OP_JG:if(!(c->ctx.regs.flags&(VPU_FLAG_ZERO|VPU_FLAG_NEGATIVE)))c->ctx.regs.pc=i->imm;return VPU_OK;case VPU_OP_JL:if(c->ctx.regs.flags&VPU_FLAG_NEGATIVE)c->ctx.regs.pc=i->imm;return VPU_OK;case VPU_OP_PUSH:s=rr(c,i->dst,&a);if(!s)s=stack_push(c,a);break;case VPU_OP_POP:s=stack_pop(c,&a);if(!s)s=rw(c,i->dst,a);break;case VPU_OP_CALL:if(i->imm<0)s=VPU_ERR_INVALID;else{s=stack_push(c,c->ctx.regs.pc);if(!s)c->ctx.regs.pc=i->imm;}return s;case VPU_OP_RET:s=stack_pop(c,&a);if(!s)c->ctx.regs.pc=a;return s;case VPU_OP_HALT:c->ctx.state=VPU_CORE_HALTED;return VPU_OK;default:return VPU_ERR_DECODE;}return s;}
vpu_status_t vpu_execute_program(vpu_core_t*c,const uint8_t*p,size_t n,size_t max,size_t*steps){if(!c||!p)return VPU_ERR_NULL;size_t count=0;while(c->ctx.state!=VPU_CORE_HALTED&&count<max){if(c->ctx.regs.pc>n||n-c->ctx.regs.pc<12)return VPU_ERR_BOUNDS;vpu_instruction_t ins;size_t used=0;vpu_status_t s=vpu_decode(p+c->ctx.regs.pc,n-c->ctx.regs.pc,&ins,&used);if(s)return s;c->ctx.regs.ir=ins.opcode;uint64_t old=c->ctx.regs.pc;c->ctx.regs.pc+=used;s=vpu_execute_instruction(c,&ins);if(s){c->ctx.error=s;return s;}if(c->ctx.regs.pc==old)c->ctx.regs.pc+=used;count++;}if(steps)*steps=count;if(c->ctx.state!=VPU_CORE_HALTED&&count==max)return VPU_ERR_INVALID;return VPU_OK;}
